### ISSUE TITLE
Live demo does not work

### ISSUE THREAD

**Issue by BarnabasSzabolcs** [grishkovelli/vue-audio-recorder#40]
https://jsfiddle.net/grishkovelli/rb1anxyj/ does not work on Chrome, Firefox and Safari 11.1.2 (13605.3.8), on mac.

On chrome: "35:15 Uncaught TypeError: console.debug is not a function" in the status.

**Comment by impronta48** [comment]
Yes, same problem here. You can fix changing console.debug in console.log

Now it works
